-- database: Exobot.sqlite
CREATE TABLE IF NOT EXISTS IABot (
    IdIABot        INTEGER PRIMARY KEY AUTOINCREMENT,
    Nombre         TEXT NOT NULL UNIQUE,
    Observacion    TEXT,
    FechaCrea      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ExaBot (
    IdExaBot       INTEGER PRIMARY KEY AUTOINCREMENT,
    IdIABot        INTEGER NOT NULL,
    Nombre         TEXT NOT NULL,
    Serie          TEXT NOT NULL,
    CONSTRAINT fk_IABot
    FOREIGN KEY (IdIABot)
    REFERENCES IABot(IdIABot)
);